services:

  backend:
    build: 
      dockerfile: dockerfile
    depends_on: 
    - "db" 
    ports:
      - 3000:3000
    command: npm run start:docker
    volumes: 
      - ./src:/usr/src/app/src
      - ./prisma:/usr/src/app/prisma
    environment:
      - DATABASE_URL=postgresql://postgres:123456@db:5432/medicIa?schema=public
      - PORT=3000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - JWT_SECRET=${JWT_SECRET}

  db:
    image: postgres:16.2
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=medicIa
